# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'

config 		= YAML.load_file 'config.yaml'
host_config	= config['host']

Vagrant.configure("2") do |config|

  config.vm.box = "openwis/centos7"

  config.vm.hostname = "ow4-dev"

  # Portal Web Access (will switch to Apache when configured)
  config.vm.network "forwarded_port", guest: 8080, host: 10080, host_ip: "localhost"
  # Portal remote debug
  config.vm.network "forwarded_port", guest: 8000, host: 18000, host_ip: "localhost"

  config.vm.network "private_network", ip: "192.168.54.101"

  config.vm.synced_folder host_config['portal_workspace'], "/tmp/portal_workspace"
  config.vm.synced_folder "../provisioning", "/tmp/provisioning"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
	  vb.cpus = 2
  end

  config.vm.provision "puppet" do |vagrant|
    vagrant.manifest_file     = "vagrant.pp"
    vagrant.manifests_path    = "provisioning/manifests"
    vagrant.hiera_config_path = "provisioning/hiera.yaml"
    vagrant.options           = "--strict_variables --parser future"
  end

  config.vm.provision "puppet" do |allinone|
    allinone.manifest_file     = "allinone.pp"
    allinone.manifests_path    = "provisioning/manifests"
    allinone.module_path       = "../provisioning/puppet/modules"
    allinone.hiera_config_path = "provisioning/hiera.yaml"
    allinone.options           = "--strict_variables --parser future"
  end
end
